[supervisord]
nodaemon=true
logfile=/data/logs/supervisord.log
pidfile=/tmp/supervisord.pid

[program:gunicorn]
command=/usr/local/bin/gunicorn pretix.wsgi --name pretix --workers 1 --threads 2 --max-requests 1200 --max-requests-jitter 50 --log-level info --bind 0.0.0.0:8000
directory=/pretix/src
user=pretixuser
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:celery]
command=/usr/local/bin/celery -A pretix.celery_app worker -l info --concurrency 1 -Q celery,default,checkout,mail,background,notifications
directory=/pretix/src
user=pretixuser
autostart=true
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
